/**
 * Book Type Definitions
 * 
 * This module defines TypeScript interfaces for book-related data structures
 * used throughout the application.
 * 
 * @module types/book
 */

/**
 * Book Interface
 * 
 * Represents a complete book entity as stored in the database and
 * returned from the API.
 * 
 * @interface Book
 * 
 * @property {number} id - Unique identifier for the book (auto-generated by database)
 * @property {string} title - Title of the book (required, max 200 characters)
 * @property {string} author - Author name (required, max 100 characters)
 * @property {string} [description] - Optional detailed description (max 2000 characters)
 * 
 */
export interface Book {
  id: number;
  title: string;
  author: string;
  description?: string;
}

/**
 * BookFormData Interface
 * 
 * Represents book data submitted through forms (create/update operations).
 * Excludes the 'id' field since it's auto-generated by the database.
 * 
 * @interface BookFormData
 * 
 * @property {string} title - Title of the book (required, max 200 characters)
 * @property {string} author - Author name (required, max 100 characters)
 * @property {string} [description] - Optional detailed description (max 2000 characters)
 */
export interface BookFormData {
  title: string;
  author: string;
  description?: string;
}
